SUB_DEPTH = ../../../..
include $(KBUILD_PATH)/subheader.kmk

#
# virtioexample
#
DLLS += virtioexample
virtioexample_TEMPLATE = VBOXR3
virtioexample_SOURCES = ../VirtIOModern/virtioPCI.cpp \
					    virtioexample.cpp
					  
virtioexample_LIBS = $(LIB_RUNTIME) $(LIB_VMM)

include $(FILE_KBUILD_SUB_FOOTER)